# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: slow_control.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='slow_control.proto',
  package='slow_control',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12slow_control.proto\x12\x0cslow_control\"~\n\x0bUserCommand\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x31\n\x04\x61rgs\x18\x02 \x03(\x0b\x32#.slow_control.UserCommand.ArgsEntry\x1a+\n\tArgsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"y\n\nUserUpdate\x12\x30\n\x07updates\x18\x01 \x03(\x0b\x32\x1f.slow_control.UserUpdate.Update\x1a\x39\n\x06Update\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\x10\n\x08variable\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\tb\x06proto3')
)




_USERCOMMAND_ARGSENTRY = _descriptor.Descriptor(
  name='ArgsEntry',
  full_name='slow_control.UserCommand.ArgsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='slow_control.UserCommand.ArgsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='slow_control.UserCommand.ArgsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=162,
)

_USERCOMMAND = _descriptor.Descriptor(
  name='UserCommand',
  full_name='slow_control.UserCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='slow_control.UserCommand.command', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='args', full_name='slow_control.UserCommand.args', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_USERCOMMAND_ARGSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=162,
)


_USERUPDATE_UPDATE = _descriptor.Descriptor(
  name='Update',
  full_name='slow_control.UserUpdate.Update',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device', full_name='slow_control.UserUpdate.Update.device', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='variable', full_name='slow_control.UserUpdate.Update.variable', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='slow_control.UserUpdate.Update.value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=228,
  serialized_end=285,
)

_USERUPDATE = _descriptor.Descriptor(
  name='UserUpdate',
  full_name='slow_control.UserUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='updates', full_name='slow_control.UserUpdate.updates', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_USERUPDATE_UPDATE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=285,
)

_USERCOMMAND_ARGSENTRY.containing_type = _USERCOMMAND
_USERCOMMAND.fields_by_name['args'].message_type = _USERCOMMAND_ARGSENTRY
_USERUPDATE_UPDATE.containing_type = _USERUPDATE
_USERUPDATE.fields_by_name['updates'].message_type = _USERUPDATE_UPDATE
DESCRIPTOR.message_types_by_name['UserCommand'] = _USERCOMMAND
DESCRIPTOR.message_types_by_name['UserUpdate'] = _USERUPDATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserCommand = _reflection.GeneratedProtocolMessageType('UserCommand', (_message.Message,), dict(

  ArgsEntry = _reflection.GeneratedProtocolMessageType('ArgsEntry', (_message.Message,), dict(
    DESCRIPTOR = _USERCOMMAND_ARGSENTRY,
    __module__ = 'slow_control_pb2'
    # @@protoc_insertion_point(class_scope:slow_control.UserCommand.ArgsEntry)
    ))
  ,
  DESCRIPTOR = _USERCOMMAND,
  __module__ = 'slow_control_pb2'
  # @@protoc_insertion_point(class_scope:slow_control.UserCommand)
  ))
_sym_db.RegisterMessage(UserCommand)
_sym_db.RegisterMessage(UserCommand.ArgsEntry)

UserUpdate = _reflection.GeneratedProtocolMessageType('UserUpdate', (_message.Message,), dict(

  Update = _reflection.GeneratedProtocolMessageType('Update', (_message.Message,), dict(
    DESCRIPTOR = _USERUPDATE_UPDATE,
    __module__ = 'slow_control_pb2'
    # @@protoc_insertion_point(class_scope:slow_control.UserUpdate.Update)
    ))
  ,
  DESCRIPTOR = _USERUPDATE,
  __module__ = 'slow_control_pb2'
  # @@protoc_insertion_point(class_scope:slow_control.UserUpdate)
  ))
_sym_db.RegisterMessage(UserUpdate)
_sym_db.RegisterMessage(UserUpdate.Update)


_USERCOMMAND_ARGSENTRY._options = None
# @@protoc_insertion_point(module_scope)
