# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1086, 573)
        self.groupBox_5 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_5.setGeometry(QtCore.QRect(570, 220, 511, 111))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        self.label_10.setGeometry(QtCore.QRect(300, 20, 101, 32))
        self.label_10.setObjectName("label_10")
        self.layoutWidget_4 = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget_4.setGeometry(QtCore.QRect(20, 50, 471, 31))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_3.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_3.addWidget(self.pushButton_7)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_3.addWidget(self.lineEdit_7)
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(570, 110, 501, 101))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(410, 20, 81, 31))
        self.label_7.setObjectName("label_7")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 50, 471, 33))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_2.addWidget(self.lineEdit_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_2.addWidget(self.lineEdit_6)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setGeometry(QtCore.QRect(240, 20, 91, 31))
        self.label_8.setObjectName("label_8")
        self.groupBox_6 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_6.setGeometry(QtCore.QRect(570, 330, 221, 71))
        self.groupBox_6.setObjectName("groupBox_6")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_9.setGeometry(QtCore.QRect(80, 30, 110, 21))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_11 = QtWidgets.QLabel(self.groupBox_6)
        self.label_11.setGeometry(QtCore.QRect(10, 20, 61, 32))
        self.label_11.setObjectName("label_11")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(570, 20, 501, 91))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(430, 20, 51, 32))
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(280, 20, 51, 32))
        self.label_5.setObjectName("label_5")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 50, 471, 33))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_3.setReadOnly(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_4.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_4.addWidget(self.lineEdit_4)
        self.fanAlertLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.fanAlertLineEdit.setEnabled(True)
        self.fanAlertLineEdit.setGeometry(QtCore.QRect(10, 26, 171, 21))
        self.fanAlertLineEdit.setAutoFillBackground(False)
        self.fanAlertLineEdit.setStyleSheet("background-color: rgb(238, 238, 211);")
        self.fanAlertLineEdit.setFrame(False)
        self.fanAlertLineEdit.setReadOnly(True)
        self.fanAlertLineEdit.setObjectName("fanAlertLineEdit")
        self.groupBox_7 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_7.setGeometry(QtCore.QRect(570, 400, 221, 71))
        self.groupBox_7.setObjectName("groupBox_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_8.setGeometry(QtCore.QRect(110, 30, 91, 21))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_12 = QtWidgets.QLabel(self.groupBox_7)
        self.label_12.setGeometry(QtCore.QRect(20, 20, 101, 32))
        self.label_12.setObjectName("label_12")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(820, 330, 201, 141))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_1 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_1.setGeometry(QtCore.QRect(10, 30, 117, 32))
        self.pushButton_1.setObjectName("pushButton_1")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(130, 110, 39, 16))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(130, 70, 44, 16))
        self.label.setObjectName("label")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_1.setGeometry(QtCore.QRect(20, 70, 104, 21))
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 110, 105, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 541, 551))
        self.tabWidget.setObjectName("tabWidget")
        self.Currents = QtWidgets.QWidget()
        self.Currents.setObjectName("Currents")
        self.graphicsView = QtWidgets.QGraphicsView(self.Currents)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 520, 520))
        self.graphicsView.setObjectName("graphicsView")
        self.tabWidget.addTab(self.Currents, "")
        self.Voltages = QtWidgets.QWidget()
        self.Voltages.setObjectName("Voltages")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.Voltages)
        self.graphicsView_2.setGeometry(QtCore.QRect(0, 0, 520, 520))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.tabWidget.addTab(self.Voltages, "")
        self.Temp = QtWidgets.QWidget()
        self.Temp.setObjectName("Temp")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.Temp)
        self.graphicsView_3.setGeometry(QtCore.QRect(0, 0, 520, 520))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.tabWidget.addTab(self.Temp, "")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(570, 490, 114, 32))
        self.pushButton.setObjectName("pushButton")
        self.checkbox = QtWidgets.QCheckBox(Dialog)
        self.checkbox.setGeometry(QtCore.QRect(575, 520, 114, 32)) #x,y, length ,width?
        self.checkbox.setObjectName("checkbox")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "pSCT"))
        self.groupBox_5.setTitle(_translate("Dialog", "Shutter control"))
        self.label_10.setText(_translate("Dialog", "Current position"))
        self.pushButton_6.setText(_translate("Dialog", "Open"))
        self.pushButton_7.setText(_translate("Dialog", "Close"))
        self.groupBox_4.setTitle(_translate("Dialog", "Camera power"))
        self.label_7.setText(_translate("Dialog", "HV Current"))
        self.pushButton_4.setText(_translate("Dialog", "Enable"))
        self.pushButton_5.setText(_translate("Dialog", "Disable"))
        self.label_8.setText(_translate("Dialog", "Supply Current"))
        self.groupBox_6.setTitle(_translate("Dialog", "Chiller monitor"))
        self.label_11.setText(_translate("Dialog", "Pressure"))
        self.groupBox_2.setTitle(_translate("Dialog", "Fan"))
        self.label_6.setText(_translate("Dialog", "Current"))
        self.label_5.setText(_translate("Dialog", "Voltage"))
        self.pushButton_2.setText(_translate("Dialog", "Fans ON"))
        self.pushButton_3.setText(_translate("Dialog", "Fans OFF"))
        self.groupBox_7.setTitle(_translate("Dialog", "Networking monitor"))
        self.label_12.setText(_translate("Dialog", "PTP packages"))
        self.groupBox.setTitle(_translate("Dialog", "Camera Positiion"))
        self.pushButton_1.setText(_translate("Dialog", "Get position"))
        self.label_2.setText(_translate("Dialog", "El/deg"))
        self.label.setText(_translate("Dialog", "Az/deg"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Currents), _translate("Dialog", "Currents"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Voltages), _translate("Dialog", "Voltages"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Temp), _translate("Dialog", "Temp"))
        self.pushButton.setText(_translate("Dialog", "Update"))
        self.checkbox.setText(_translate("Dialog", "Status view"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

